name: Npm Package

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: 
                    - windows-latest
                    # - ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: yarn
            - run: git ls-files
            - run: tsc
            - run: yarn test
            # - name: Bump version
            #   if: matrix.os == 'ubuntu-latest'
            #   uses: remorses/bump-version@js
            #   with:
            #       version_file: VERSION
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - run: yarn publish
            #   if: matrix.os == 'ubuntu-latest'
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
